### PR TITLE
Xuefeng develop

### PR DESCRIPTION
**Pull request by xyan12345**
Program Data load

### CODE REVIEW

**Comment by rraub** [comment]
you have some lint errors to fix

**Comment by xyan12345** [comment]
I am trying to fix it. It has format issues like following picture. I have correct number of space. If i modify it  as terminal said, i will have invalid Json.
f0a9fb4c-ffdf-46b8-b615-816282cc6a01
It is valid right now. What is your suggestion? 
3ee34b2b-58f0-4e38-a5eb-84c0526175c9
Thanks,
Xuefeng

**Comment by rraub** [comment]
Did you mean to delete the `"promote a CIO"` program?

**Comment by rraub** [comment]
Yes its valid, but we want more than just validation, we want to match our coding style.
To summarize the errors your getting:
- [x] add `export default` to the first line just like all the other js files
- [x] replace all double quotes with single quotes (watch out for one apostrophe)
- [x] remove the quotes on the variable names since they dont contain spaces quotes are not necessary
- [x] add a semi colin as the last thing. (this isn't a requirement for the language, but it is in our coding standards)

**Comment by xyan12345** [comment]
got it! Thanks!

**Comment by xyan12345** [comment]
I fixed it.Still have one more error. 
210b6d9c-13da-45c1-b924-9378da3a774b
Unexpected toke
c3913499-6cec-4322-a75e-6a94839e1630
I dont know why..

**Comment by rraub** [comment]
It looks like you have the fancy (also known as curly) single quotes (like the ones Microsoft Word uses) instead of the normal straight quote character. Did you edit the file in word? or something?

http://practicaltypography.com/straight-and-curly-quotes.html

**Comment by xyan12345** [comment]
thanks, that is right! I still have issue like this
e9cc4d2b-7c8e-488d-bb2b-c4a7dc438694
i checked line 16, nothing special
c64b4c7d-e92f-478e-bcbd-4f4f25a76bda
dont know why

**Comment by rraub** [comment]
You should look at the end of line 15.

**Comment by xyan12345** [comment]
Thanks! Got it! it reports the line number before that line

**Comment by rraub** [comment]
Thats right, because it gets to line 16 and expects a comma and doesn't get a comma.

**Pull request merged**
