### PR TITLE
Tuyenho develop

### PR DESCRIPTION
**Pull request by Tuyenho**
Add data to action.js, game-reducer.js and game.js fix event-page.jsx and main-page.jsx

### CODE REVIEW

**Comment by rraub** [comment]
You have merge conflicts

**Comment by rraub** [comment]
If you can get the tests working in issue #118 then this branch is ready to go

**Comment by Tuyenho** [comment]
i thought i fixed the merge conflicts before? i don't know what the issues is.

**Comment by rraub** [comment]
There was another pull request that got merged into develop and that had some changes to files you've modified here.

**Pull request merged**
