### PR TITLE
Mark capstone develop

### PR DESCRIPTION
**Pull request by msdickinson**
Added Programs, Program, Program List, Program List Item

### CODE REVIEW

**Comment by msdickinson** [comment]
How Do I run the lint for this? So I can fix Travis errors. with out having to make a pull request each time?

**Comment by idmontie** [comment]
`npm run lint`

**Comment by idmontie** [comment]
I'm not sure why you have the **entire**  `.meteor` folder tracked.

**Comment by idmontie** [comment]
What you will want to do is checkout develop, make a new branch, cherry pick commit 62be26b and then push that and kill this branch.

**Pull request closed without merging**
